import Head from "next/head";
import useTranslation from "next-translate/useTranslation";
import Link from "next/link";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Image from "next/image";
import Stroh from "../public/background.jpg";

export default function Home() {
    const { t } = useTranslation("common");
    return (
        <div>
            <Head>
                <title>Strohtektur</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main className="flex flex-col  border-y-2 border-y-black ">
				<section className="pt-28 px-6 bg-stroh grid md:grid-cols-2 text-center md:text-left">
                    <div className="flex flex-col gap-4">
                        <h1 className="text-6xl font-bold">N.O.W. Lindow</h1>
                        <h2 className="text-4xl ">
							{t("slogan")}
                        </h2>
                        <h3 className="text-2xl">
							{t("slogan2")}
                        </h3>

						<div className="bg-black max-w-fit p-2 mx-auto md:mx-0">
                            <h2 className="text-white text-3xl">
								{t("callout")}
                            </h2>
                        </div>
                        <h4 className="text-xl animate-bounce hover:animate-none">
								{t("callout2")}
                        </h4>
                    </div>
                    <div className="mx-auto ">
                        <Image
                            src={Stroh}
                            alt="Bild von Stroh"
                            height={500}
                            className="rounded-xl"
                        />
                    </div>
                </section>
                <section className="h-screen flex flex-col gap-4 justify-center items-center bg-stroh">
					<div className="text-2xl text-center w-1/2 mb-10 md:mb-20">
						<p>{t("textUs")}</p>
						<span>{t("infoCallOut")}</span>
                    </div>
                    <div className="flex gap-4">
                        <a
                            href="mailto:info@strohtektur.de"
                            className="border-black px-1 py-1 rounded-sm border-2 hover:bg-black hover:text-white"
                        >
                            Email
                        </a>

                        <div className="border-black px-1 py-1 rounded-sm border-2 hover:bg-black hover:text-white">
                            <Link href="/support">N.O.W. Lindow</Link>
                        </div>

                        <a
                            target="_blank"
                            rel="noreferrer"
                            href="https://goo.gl/maps/Q2wHyFSN4Yhk1G5M7"
                            className="border-black px-1 py-1 rounded-sm border-2 hover:bg-black hover:text-white"
                        >
                            Maps
                        </a>
                    </div>
                </section>
                <Footer />
            </main>
        </div>
    );
}
